name: PhotoFilters
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.5.8+11
  cupertino_icons: ^1.0.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  liquid_swipe: ^1.5.0
  path_provider: ^1.6.24
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
